# Generated by Django 6.0.7 on 2026-07-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='One option per line. Used when question_type is "Choice"'),
        ),
    ]
