# Generated by Django 6.0.7 on 2026-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_selections',
            field=models.PositiveIntegerField(default=3, help_text='Maximum selections allowed for multi-select questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='multi_text_count',
            field=models.PositiveIntegerField(default=3, help_text='Number of separate text inputs for multi-text questions'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='One option per line. Used when question_type is Choice or Multi-select'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('multi_select', 'Multi-select'), ('multi_text', 'Multi-text (multiple short texts)')], default='text', max_length=20),
        ),
    ]
