# Generated by Django 6.0.7 on 2026-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_response_status_and_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_images',
            field=models.TextField(blank=True, help_text='Optional image URL per line. Line order should match the options above for multi-select questions'),
        ),
    ]
